name: family_tree_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: any
  graphview: ^1.2.0
  # Firebase
  firebase_core: ^2.15.1
  firebase_core_web: ^2.7.0
  cloud_firestore: ^4.9.1
  cloud_firestore_web: ^3.7.0
  firebase_storage: ^11.2.6
  firebase_storage_web: ^3.6.6
  firebase_auth: ^4.9.0
  firebase_auth_web: ^5.8.0
  firebase_ui_auth: ^1.6.5
  #
  email_validator: ^2.1.17

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/people/
